id: P88C74FD7
initial_creation_type: input
source_metadata:
  title: Dying and the Bardos
  language: de
  description: 'Lotsawa House presents the following texts as part of our Dying and
    Bardos Series:'
  volume:
    0681fbe7a41e487c98e44bf18107cb18:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Dying
    b901c668346741ad940af9ad6937a17c:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Dying
    047aa050d30243b7a9c6193a7e637a71:
      title: Advice for Hor Özer
      parent: Dying
    615e2bd1fe23488d93250435160ebb62:
      title: Advice for a Dying Practitioner
      parent: Dying
    1510693df71f468f974c1ab0c6e62b79:
      title: Aspiration at the Moment of Death
      parent: Dying
    f5f47073ee2e45ecad0b1c21b55cf990:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Dying
    08c615a9f08b40b88ac63106bc2ee2c4:
      title: A Wondrous Instruction for the Moment of Death
      parent: Dying
    db5f96e8c4094f05820970c2a29cdb21:
      title: Meditation on Amitābha
      parent: Dying
    b7de9a7080ec441790bacd86f0d27c56:
      title: The Root Verses on the Six Bardos
      parent: Bardos
    76075eb0204948c49f37b47ea86a668d:
      title: 'Crucial Advice: A Complete Set of Instructions for the Bardos'
      parent: Bardos
    6b440052375c4a9fa8c9cf13673bd350:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Bardos
    7525dfcdf97445f9a43341a03db21e1c:
      title: A Brief Introduction to the Bardos
      parent: Bardos
    837a705ffdab45b39649d5ea9821be4b:
      title: 'Fostering Recollection to Dispel the Torment of Deluded Perception:
        An Aspiration for the Bardos'
      parent: Prayers
    af2dbbce5acc438cbfddf387fa2e6172:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Prayers
    b8368750d1ed4391a8e71fdac5b053b1:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Prayers
    f5a3ae5514a941008a9e86b91f4ed662:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
created_at: '2022-03-01T03:30:40.702649'
last_modified_at: '2022-03-01T03:30:40.702652'
